-- 002_campaigns.sql — Campaign Domain (STRICT SEPARATION)
-- Enterprise-ready campaign attribution capability.
--
-- Principles (mirrors referrals):
-- - campaign_code is the stable campaign definition identity (human-usable, shareable).
-- - campaign_code is GENERATED by the service on create (NOT supplied by clients).
-- - campaign_track_id is created ONLY when a campaign code is validated (post-scan).
-- - All post-validation writes/events MUST reference campaign_track_id.
-- - Policies are versioned and may be tenant-specific (or global when tenant_code is NULL).
--
-- Notes on naming:
-- - Replaced "sticker" with "segment" as the primary targeting dimension (EASY/ASPIRE/PREMIER/...).
-- - If you later need BOTH "segment" types (e.g., Personal/Private vs EASY/PREMIER),
--   add a second column (e.g., business_segment) rather than overloading this field.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------
-- Campaign definitions (created by marketing/admin)
-- -----------------------------
-- campaign_code generation:
-- - The API/service generates campaign_code from (tenant_code + segment + name + suffix)
--   e.g., FNB-PREMIER-BURGER-FRIDAY-7K3Q
-- - DB enforces uniqueness via PRIMARY KEY / UNIQUE constraint.
CREATE TABLE IF NOT EXISTS marketing_campaigns (
  -- Stable campaign definition identity (generated by service)
  campaign_code TEXT PRIMARY KEY,

  -- Optional internal surrogate identifier (useful if you ever want to change code formats)
  campaign_id   UUID NOT NULL DEFAULT gen_random_uuid(),

  name          TEXT NOT NULL,

  -- Target segment (replaces sticker)
  segment       TEXT NOT NULL,

  -- Optional tenant/brand scope (NULL implies global)
  tenant_code   TEXT,

  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  starts_at     TIMESTAMPTZ,
  ends_at       TIMESTAMPTZ,

  -- Optional hard cap (simple usage limit; policies can implement richer caps)
  max_uses      INTEGER,
  uses_count    INTEGER NOT NULL DEFAULT 0,

  -- FIX: make attributes consistent and safe to query/index
  attributes    JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Basic sanity constraints
  CONSTRAINT campaigns_dates_chk
    CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at),
  CONSTRAINT campaigns_max_uses_chk
    CHECK (max_uses IS NULL OR max_uses >= 1),
  CONSTRAINT campaigns_uses_count_chk
    CHECK (uses_count >= 0),

  -- Ensure campaign_id is unique even though campaign_code is the stable identity
  CONSTRAINT campaigns_campaign_id_uniq UNIQUE (campaign_id)
);

-- -----------------------------
-- Idempotent upgrades (safe if table already exists)
-- -----------------------------
-- Safer pattern: add nullable first, backfill, then enforce NOT NULL + default + uniq
ALTER TABLE marketing_campaigns
  ADD COLUMN IF NOT EXISTS campaign_id UUID;

UPDATE marketing_campaigns
SET campaign_id = COALESCE(campaign_id, gen_random_uuid())
WHERE campaign_id IS NULL;

ALTER TABLE marketing_campaigns
  ALTER COLUMN campaign_id SET DEFAULT gen_random_uuid();

ALTER TABLE marketing_campaigns
  ALTER COLUMN campaign_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'campaigns_campaign_id_uniq'
  ) THEN
    ALTER TABLE marketing_campaigns
      ADD CONSTRAINT campaigns_campaign_id_uniq UNIQUE (campaign_id);
  END IF;
END $$;

-- Migrate from "sticker" -> "segment" if sticker existed previously.
-- (If "sticker" column exists, keep it for backward compatibility but prefer "segment".)
ALTER TABLE marketing_campaigns
  ADD COLUMN IF NOT EXISTS segment TEXT;

-- If you previously had "sticker" and want to backfill:
-- NOTE: This statement will fail if sticker doesn't exist; run manually if needed.
-- UPDATE marketing_campaigns SET segment = COALESCE(segment, sticker);

ALTER TABLE marketing_campaigns
  ADD COLUMN IF NOT EXISTS max_uses   INTEGER;
ALTER TABLE marketing_campaigns
  ADD COLUMN IF NOT EXISTS uses_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE marketing_campaigns
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Ensure attributes is consistent on older DBs too
ALTER TABLE marketing_campaigns
  ADD COLUMN IF NOT EXISTS attributes JSONB;

UPDATE marketing_campaigns
SET attributes = COALESCE(attributes, '{}'::jsonb)
WHERE attributes IS NULL;

ALTER TABLE marketing_campaigns
  ALTER COLUMN attributes SET DEFAULT '{}'::jsonb;

ALTER TABLE marketing_campaigns
  ALTER COLUMN attributes SET NOT NULL;

-- Optional: enforce NOT NULL segment once you’ve backfilled (apply manually when ready)
-- ALTER TABLE marketing_campaigns ALTER COLUMN segment SET NOT NULL;

-- -----------------------------
-- Indexes (definition lookups + typical filtering)
-- -----------------------------

-- Fast lookup by code (PK already indexes; explicit index is optional)
CREATE INDEX IF NOT EXISTS idx_campaigns_code
  ON marketing_campaigns (campaign_code);

-- Typical admin / runtime filters
CREATE INDEX IF NOT EXISTS idx_campaigns_tenant_segment
  ON marketing_campaigns (tenant_code, segment);

-- Active window filtering (runtime queries like: active AND now between starts/ends)
CREATE INDEX IF NOT EXISTS idx_campaigns_active_dates
  ON marketing_campaigns (is_active, starts_at, ends_at);

-- Tenant filtering
CREATE INDEX IF NOT EXISTS idx_campaigns_tenant
  ON marketing_campaigns (tenant_code);

-- Optional: only if you query within attributes
CREATE INDEX IF NOT EXISTS idx_campaigns_attributes_gin
  ON marketing_campaigns USING GIN (attributes);


-- -----------------------------
-- Campaign-level policy overrides (campaign-only)
-- -----------------------------
-- Future-proof model:
-- - versioned policies for controlled change management
-- - tenant-specific policy (tenant_code NOT NULL) overrides global (tenant_code NULL)
-- - only one active version should be used at runtime (service picks newest updated)
CREATE TABLE IF NOT EXISTS marketing_campaign_policies (
  campaign_code         TEXT NOT NULL REFERENCES marketing_campaigns(campaign_code) ON DELETE RESTRICT,
  tenant_code           TEXT,
  version               INTEGER NOT NULL DEFAULT 1,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,

  rolling_window_days   INTEGER,
  rules_json            JSONB,
  product_windows_json  JSONB,

  reward_amounts_json   JSONB,
  product_rules_json    JSONB,

  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (campaign_code, tenant_code, version)
);

-- Idempotent upgrades (safe if table already exists)
ALTER TABLE marketing_campaign_policies
  ADD COLUMN IF NOT EXISTS tenant_code          TEXT;
ALTER TABLE marketing_campaign_policies
  ADD COLUMN IF NOT EXISTS version              INTEGER NOT NULL DEFAULT 1;
ALTER TABLE marketing_campaign_policies
  ADD COLUMN IF NOT EXISTS is_active            BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE marketing_campaign_policies
  ADD COLUMN IF NOT EXISTS rolling_window_days  INTEGER;
ALTER TABLE marketing_campaign_policies
  ADD COLUMN IF NOT EXISTS rules_json           JSONB;
ALTER TABLE marketing_campaign_policies
  ADD COLUMN IF NOT EXISTS product_windows_json JSONB;
ALTER TABLE marketing_campaign_policies
  ADD COLUMN IF NOT EXISTS reward_amounts_json  JSONB;
ALTER TABLE marketing_campaign_policies
  ADD COLUMN IF NOT EXISTS product_rules_json   JSONB;

-- Index used by policy resolver (tenant-specific overrides global; newest wins)
CREATE INDEX IF NOT EXISTS idx_campaign_policies_effective
  ON marketing_campaign_policies (campaign_code, tenant_code, is_active, updated_at DESC, version DESC);


-- -----------------------------
-- Campaign Attribution / Participation Ledger
-- -----------------------------
-- This table is the campaign-domain "lineage" anchor.
-- One row represents a validated (golden thread) campaign interaction.
--
-- IMPORTANT:
-- - Pre-validation telemetry can be stored here as SCANNED.
-- - But campaign_track_id becomes the golden thread ONLY after validation.
-- - All downstream writes MUST reference campaign_track_id (not campaign_code).
CREATE TABLE IF NOT EXISTS campaign_attributions (
  campaign_track_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  campaign_code       TEXT NOT NULL REFERENCES marketing_campaigns(campaign_code) ON DELETE RESTRICT,
  tenant_code         TEXT,

  -- Customer linkage (encrypted/opaque; no raw PII)
  user_ucn_encrypted  TEXT,

  -- Telemetry signals (useful for abuse control / auditing)
  device_fingerprint  TEXT,
  ip_address          TEXT,
  qr_payload          TEXT,
  source_channel      TEXT,

  -- FIX: metadata_json consistent and safe
  metadata_json       JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Lifecycle of the attributed campaign interaction
  status              TEXT NOT NULL DEFAULT 'SCANNED',
  validation_reason   TEXT,

  scanned_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  validated_at        TIMESTAMPTZ,
  attributed_at       TIMESTAMPTZ,
  completed_at        TIMESTAMPTZ,

  CONSTRAINT campaign_attr_status_chk
    CHECK (status IN ('SCANNED', 'VALIDATED', 'ATTRIBUTED', 'COMPLETED', 'BLOCKED', 'EXPIRED', 'INVALID'))
);

-- Idempotent upgrades
ALTER TABLE campaign_attributions
  ADD COLUMN IF NOT EXISTS tenant_code        TEXT;
ALTER TABLE campaign_attributions
  ADD COLUMN IF NOT EXISTS source_channel     TEXT;
ALTER TABLE campaign_attributions
  ADD COLUMN IF NOT EXISTS metadata_json      JSONB;
ALTER TABLE campaign_attributions
  ADD COLUMN IF NOT EXISTS validation_reason  TEXT;
ALTER TABLE campaign_attributions
  ADD COLUMN IF NOT EXISTS validated_at       TIMESTAMPTZ;

-- Ensure metadata_json default/non-null on older DBs
UPDATE campaign_attributions
SET metadata_json = COALESCE(metadata_json, '{}'::jsonb)
WHERE metadata_json IS NULL;

ALTER TABLE campaign_attributions
  ALTER COLUMN metadata_json SET DEFAULT '{}'::jsonb;

ALTER TABLE campaign_attributions
  ALTER COLUMN metadata_json SET NOT NULL;

-- Lookup/indexing for common investigations + runtime queries
CREATE INDEX IF NOT EXISTS idx_campaign_attr_campaign_code
  ON campaign_attributions (campaign_code);

CREATE INDEX IF NOT EXISTS idx_campaign_attr_tenant
  ON campaign_attributions (tenant_code);

CREATE INDEX IF NOT EXISTS idx_campaign_attr_user_ucn
  ON campaign_attributions (user_ucn_encrypted);

CREATE INDEX IF NOT EXISTS idx_campaign_attr_device
  ON campaign_attributions (device_fingerprint);

CREATE INDEX IF NOT EXISTS idx_campaign_attr_status
  ON campaign_attributions (status);

-- Helpful for “most recent journey by device/user”
CREATE INDEX IF NOT EXISTS idx_campaign_attr_device_scanned_at
  ON campaign_attributions (device_fingerprint, scanned_at DESC);

CREATE INDEX IF NOT EXISTS idx_campaign_attr_user_scanned_at
  ON campaign_attributions (user_ucn_encrypted, scanned_at DESC);


-- -----------------------------
-- Optional: event stream per track (enterprise attribution/audit)
-- -----------------------------
CREATE TABLE IF NOT EXISTS campaign_track_events (
  id                BIGSERIAL PRIMARY KEY,
  campaign_track_id UUID NOT NULL REFERENCES campaign_attributions(campaign_track_id) ON DELETE RESTRICT,
  event_type        TEXT NOT NULL,
  payload_json      JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Idempotent upgrades for payload_json consistency
ALTER TABLE campaign_track_events
  ADD COLUMN IF NOT EXISTS payload_json JSONB;

UPDATE campaign_track_events
SET payload_json = COALESCE(payload_json, '{}'::jsonb)
WHERE payload_json IS NULL;

ALTER TABLE campaign_track_events
  ALTER COLUMN payload_json SET DEFAULT '{}'::jsonb;

ALTER TABLE campaign_track_events
  ALTER COLUMN payload_json SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_campaign_track_events_track
  ON campaign_track_events (campaign_track_id, created_at DESC);