apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
namespace: referrals-stage
resources:
  - ../../base
patches:
  - path: patch-api-env.yaml
    target: { kind: Deployment, name: referrals-api }
  - path: patch-api-replicas.yaml
    target: { kind: Deployment, name: referrals-api }
configMapGenerator:
  - name: referrals-config
    files:
      - logging.yaml=../../../config/logging.yaml
      - kafka.yaml=../../../config/kafka.yaml
      - db.yaml=../../../config/db.yaml
      - settings.prod.yaml=../../../config/settings.prod.yaml
images:
  - name: ghcr.io/ORG/referrals-api
    newTag: stage
  - name: ghcr.io/ORG/referrals-worker
    newTag: stage
