monitoring:
  enabled: true
  servicemonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 10s
    labels: {}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
