apiVersion: v1
kind: Secret
metadata:
  name: {{ include "referrals.fullname" . }}-secrets
type: Opaque
stringData:
  APP_DB_DSN: "{{ .Values.secrets.APP_DB_DSN }}"
  ADMIN_API_KEY: "{{ .Values.secrets.ADMIN_API_KEY }}"
  WORKER_SECRET: "{{ .Values.secrets.WORKER_SECRET }}"
  REFERRAL_CODE_SECRET: "{{ .Values.secrets.REFERRAL_CODE_SECRET }}"
  FNB_PARTNER_API_KEY: "{{ .Values.secrets.FNB_PARTNER_API_KEY }}"
  FNB_TENANT_USER_API_KEY: "{{ .Values.secrets.FNB_TENANT_USER_API_KEY }}"
  FNB_TENANT_ADMIN_API_KEY: "{{ .Values.secrets.FNB_TENANT_ADMIN_API_KEY }}"
  PNP_PARTNER_API_KEY: "{{ .Values.secrets.PNP_PARTNER_API_KEY }}"
  PNP_TENANT_USER_API_KEY: "{{ .Values.secrets.PNP_TENANT_USER_API_KEY }}"
  PNP_TENANT_ADMIN_API_KEY: "{{ .Values.secrets.PNP_TENANT_ADMIN_API_KEY }}"
  APP_SQS_QUEUE_URL: "{{ .Values.secrets.APP_SQS_QUEUE_URL }}"
  APP_SQS_DLQ_URL: "{{ .Values.secrets.APP_SQS_DLQ_URL }}"
  AWS_REGION: "{{ .Values.secrets.AWS_REGION }}"
  REDIS_URL: "{{ .Values.secrets.REDIS_URL }}"
