apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: referrals-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: referrals.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: referrals-api
                port:
                  number: 8000
  tls:
    - hosts: [referrals.example.com]
      secretName: referrals-tls
