INSERT INTO mission_definitions (
    mission_code,
    mission_name,
    mission_description,
    product,
    sub_product,
    event_type,
    goal_count,
    bonus_reward_amount,
    currency,
    is_optional,
    is_credit_related,
    requires_disclaimer,
    regulatory_tags,
    display_priority,
    mission_category,
    is_active
)
VALUES
(
    'ACCOUNT_OPENED_CORE',
    'Account opened',
    'Reward progress starts when the referred account is opened.',
    'TRANSACTIONAL',
    'DDA13',
    'ACCOUNT_OPENED',
    1,
    0,
    'ZAR',
    FALSE,
    FALSE,
    TRUE,
    '["TCF","FAIS","MARKET_CONDUCT","BANKING_CODE"]'::jsonb,
    1,
    'CORE',
    TRUE
),
(
    'ACCOUNT_ACTIVATED_CORE',
    'Account activated',
    'Reward progress continues when the referred account is activated.',
    'TRANSACTIONAL',
    'DDA13',
    'ACCOUNT_ACTIVATED',
    1,
    0,
    'ZAR',
    FALSE,
    FALSE,
    TRUE,
    '["TCF","FAIS","MARKET_CONDUCT","BANKING_CODE"]'::jsonb,
    2,
    'CORE',
    TRUE
),
(
    'ACCOUNT_FUNDED_CORE',
    'Account funded',
    'Reward progress continues when qualifying funding is completed.',
    'TRANSACTIONAL',
    'DDA13',
    'FUNDED',
    1,
    0,
    'ZAR',
    FALSE,
    FALSE,
    TRUE,
    '["TCF","FAIS","MARKET_CONDUCT","BANKING_CODE"]'::jsonb,
    3,
    'CORE',
    TRUE
);