INSERT INTO leaderboard_scoring_rules (
    leaderboard_code,
    journey_code,
    journey_version,
    product,
    sub_product,
    milestone_code,
    score_type,
    score_value,
    max_awards_per_referral,
    active,
    effective_from,
    created_at,
    updated_at
)
VALUES
('GLOBAL_TRANSACTIONAL', 'BANKING_TRANSACTIONAL', 'v1', 'TRANSACTIONAL', NULL, 'ACCOUNT_OPENED', 'MILESTONE', 20, 1, TRUE, NOW(), NOW(), NOW()),
('GLOBAL_TRANSACTIONAL', 'BANKING_TRANSACTIONAL', 'v1', 'TRANSACTIONAL', NULL, 'ACCOUNT_ACTIVATED', 'MILESTONE', 30, 1, TRUE, NOW(), NOW(), NOW()),
('GLOBAL_TRANSACTIONAL', 'BANKING_TRANSACTIONAL', 'v1', 'TRANSACTIONAL', NULL, 'FUNDED', 'MILESTONE', 50, 1, TRUE, NOW(), NOW(), NOW()),
('GLOBAL_TRANSACTIONAL', 'BANKING_TRANSACTIONAL', 'v1', 'TRANSACTIONAL', NULL, 'DEBIT_ORDER_SWITCHED', 'MILESTONE', 20, 1, TRUE, NOW(), NOW(), NOW()),
('GLOBAL_TRANSACTIONAL', 'BANKING_TRANSACTIONAL', 'v1', 'TRANSACTIONAL', NULL, 'SALARY_SWITCHED', 'MILESTONE', 20, 1, TRUE, NOW(), NOW(), NOW()),
('GLOBAL_TRANSACTIONAL', 'BANKING_TRANSACTIONAL', 'v1', 'TRANSACTIONAL', NULL, 'FIRST_TRANSACTION_COMPLETED', 'MILESTONE', 15, 1, TRUE, NOW(), NOW(), NOW()),
('GLOBAL_TRANSACTIONAL', 'BANKING_TRANSACTIONAL', 'v1', 'TRANSACTIONAL', NULL, 'COMPLETION_BONUS', 'BONUS', 25, 1, TRUE, NOW(), NOW(), NOW());