INSERT INTO mission_definitions (
    mission_code,
    mission_name,
    mission_description,
    product,
    sub_product,
    event_type,
    goal_count,
    bonus_reward_amount,
    currency,
    is_optional,
    is_credit_related,
    requires_disclaimer,
    regulatory_tags,
    display_priority,
    mission_category,
    is_active
)
VALUES
(
    'COMPLETE_1_REFERRAL',
    'First successful referral',
    'A bonus reward may be applied when your first referral completes qualifying actions.',
    NULL,
    NULL,
    'REFERRAL_COMPLETED',
    1,
    50,
    'ZAR',
    TRUE,
    FALSE,
    TRUE,
    '["TCF","FAIS","MARKET_CONDUCT","BANKING_CODE"]'::jsonb,
    10,
    'MILESTONE',
    TRUE
),
(
    'COMPLETE_3_REFERRALS',
    '3 successful referrals',
    'A bonus reward may be applied when three referrals complete qualifying actions.',
    NULL,
    NULL,
    'REFERRAL_COMPLETED',
    3,
    150,
    'ZAR',
    TRUE,
    FALSE,
    TRUE,
    '["TCF","FAIS","MARKET_CONDUCT","BANKING_CODE"]'::jsonb,
    20,
    'MILESTONE',
    TRUE
),
(
    'COMPLETE_5_REFERRALS',
    '5 successful referrals',
    'A bonus reward may be applied when five referrals complete qualifying actions.',
    NULL,
    NULL,
    'REFERRAL_COMPLETED',
    5,
    300,
    'ZAR',
    TRUE,
    FALSE,
    TRUE,
    '["TCF","FAIS","MARKET_CONDUCT","BANKING_CODE"]'::jsonb,
    30,
    'MILESTONE',
    TRUE
);